### ISSUE TITLE
Allow root page to be controlled by menu filters

### ISSUE THREAD

**Issue by CrispinF** [cloudscribe/cloudscribe.SimpleContent#496]
@abomadi asked in Gitter 

> im not able to take out the homepage link from TopNav menu, i even tried to write a non existing component view in the page settings but still appears, any idea how to achieve this ?

We replied:

> we have previously done this by creating a local override of the view \Views\Shared\Components\Navigation\Bootstrap4TopNavWithDropdowns.cshtml and commenting out the first 'li' element.

When we go to the Settings of the root page, we have controls including the Menu Filter, but the root node in the menu doesn't respect the setting.

If possible we'd like to make this node respect those settings (testing that this doesn't cause other problems).  
If that works fine, could it also respect "View Roles"?

**Comment by joeaudette** [comment]
This would be a navigation component issue but I can tell you it is a bad idea.

Home is a special node it is the root of the tree all page hang off of and it also corresponds to / not just /home.
If you want to remove home from top nav you should edit the view as recommended before.

**Comment by CrispinF** [comment]
@joeaudette thanks - if the code change simply results in not rendering the 'li' element if the Menu Filter wants in in (say) breadcrumbs and sitemap but not topnav, doesn't this amount to the same as overriding the view with it commented out? Can you explain why it's a bad idea?

**Comment by JimKerslake** [comment]
Ho @joeaudette 
I was just looking at the PagesNavigationTreeBuilder in SimpleContent, where it builds the rootNav node...   Seems to me that if you just set the ComponentVisibility property on the root node here, from MenuFilters property of the page, then the visibility of that navigation links seems to behjave as wanted.  But...  haven't had time to test out yet what other crazy things might ensue from that change...!

**Comment by JimKerslake** [comment]
PS - I mean it would behave as wanted if you wrap the link in the view like this:
` @if (await Model.ShouldAllowView(Model.RootNode))`

**Comment by abomadi** [comment]
Thanks @CrispinF for opening this ticket, i have tried editing navigation.xml component Visibility also Menu Filter in page settings and seems it does not work, i will give your workaround a try and i might also remove the node it self from the navigation.xml

**Comment by CrispinF** [comment]
OK we've released new nugets that permit the home page to respect menu filters and role filters. 
The menu filtering is good. We can set the filter for our home page to "breadcrumbs,sitemap" and it disappears from the main navbar. 
So long as we have a prominent link in the header, this is good for accessibility.
@abomadi please see if this works nicely for you. As I am sure you have discovered, you must not remove this node from navigation.xml.
But the role filtering is less good. If not in configured role (e.g. "Authenticated users") we see "Page not found" whereas I was hoping to be redirected to a login. I will log a separate issue for this as it is pre-existing behaviour (some pages redirect to login, others say "page not found").

**Comment by CrispinF** [comment]
@joeaudette perhaps you could review this too and see if there are any undesirable consequences around the menu filters?

**Comment by joeaudette** [comment]
seems ok.

**Comment by CrispinF** [comment]
All good and tested, closing

**Comment by abomadi** [comment]
Hi @CrispinF i am trying to test this functionality, what version of package should be there, as i tried Menu Filters with 'none' or 'breadcrumbs,sitemap' and the roles view empty, the page still appearing !

**Comment by CrispinF** [comment]
@abomadi if you "Manage Nuget packages" and accept all updates, you should get the change.  Specifically this is included in 5.0.4 of cloudscribe.SimpleContent.Web
